'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');

test('phase902: desktop patrol admin render and docs surface latest promotion add-only', () => {
  const js = fs.readFileSync('apps/admin/assets/admin_app.js', 'utf8');
  const runbook = fs.readFileSync('docs/RUNBOOK_ADMIN_OPS.md', 'utf8');
  const lineRunbook = fs.readFileSync('docs/RUNBOOK_LINE_DESKTOP_PATROL.md', 'utf8');
  const ssot = fs.readFileSync('docs/SSOT_ADMIN_UI_OS.md', 'utf8');
  const architecture = fs.readFileSync('docs/LINE_DESKTOP_PATROL_ARCHITECTURE.md', 'utf8');
  const dataMap = fs.readFileSync('docs/DATA_MAP.md', 'utf8');

  assert.ok(js.includes("title: 'Latest promotion'"));
  assert.ok(js.includes("title: 'Latest review bundle'"));
  assert.ok(js.includes("title: 'Latest approval lane'"));
  assert.ok(js.includes("title: 'Latest promotion batch'"));
  assert.ok(js.includes('promotion.latestArtifactKind'));
  assert.ok(js.includes('promotion.latestArtifactStatus'));
  assert.ok(js.includes('promotion.latestDraftPrRef'));
  assert.ok(js.includes('promotionReview.latestReviewArtifactKind'));
  assert.ok(js.includes('promotionReview.codeEditTaskRef'));
  assert.ok(js.includes('promotionReview.codeApplyDraftRef'));
  assert.ok(js.includes('promotionReview.codeReviewPacketRef'));
  assert.ok(js.includes('promotionApproval.approvalStage'));
  assert.ok(js.includes('promotionApproval.validationCommandCount'));
  assert.ok(js.includes('promotionApproval.remainingCommandCount'));
  assert.ok(js.includes('promotionApproval.codeApplyRecordRef'));
  assert.ok(js.includes('promotionApproval.codeApplyEvidenceRef'));
  assert.ok(js.includes('promotionApproval.codeApplyEvidencePromptRef'));
  assert.ok(js.includes('promotionApproval.latestArtifactRef'));
  assert.ok(js.includes('promotionApproval.latestPromptRef'));
  assert.ok(js.includes('promotionApproval.operatorInstructions'));
  assert.ok(js.includes('promotionApproval.evidenceRequirements'));
  assert.ok(js.includes('promotionApproval.expectedOutputs'));
  assert.ok(js.includes('promotionApproval.stopConditions'));
  assert.ok(js.includes('promotionApproval.expectedOutputCount'));
  assert.ok(js.includes('promotionApproval.stopConditionCount'));
  assert.ok(js.includes('expectedOutputs='));
  assert.ok(js.includes('stopConditions='));
  assert.ok(js.includes('promotionApproval.nextCommand'));
  assert.ok(js.includes('promotionApproval.remainingCommands'));
  assert.ok(js.includes('qualityPatrolApprovalPlanHash'));
  assert.ok(js.includes('pendingPlanHash'));
  assert.ok(js.includes("Copy next command"));
  assert.ok(js.includes("Copy remaining commands"));
  assert.ok(js.includes("Copy latest prompt path"));
  assert.ok(js.includes("Copy latest artifact path"));
  assert.ok(js.includes("Copy patch request path"));
  assert.ok(js.includes("Copy code apply task path"));
  assert.ok(js.includes("Copy code apply signoff path"));
  assert.ok(js.includes("Copy code apply record path"));
  assert.ok(js.includes("Copy code apply evidence path"));
  assert.ok(js.includes("Copy validation commands"));
  assert.ok(js.includes("Copy evidence prompt path"));
  assert.ok(js.includes("Copy evidence requirements"));
  assert.ok(js.includes("Copy expected outputs"));
  assert.ok(js.includes("Copy stop conditions"));
  assert.ok(js.includes("Copy operator instructions"));
  assert.ok(js.includes("Copy worktree path"));
  assert.ok(js.includes("Copy candidate edit paths"));
  assert.ok(js.includes("Plan next step"));
  assert.ok(js.includes("Run next step"));
  assert.ok(js.includes('/api/admin/quality-patrol/desktop-approval/plan'));
  assert.ok(js.includes('/api/admin/quality-patrol/desktop-approval/execute'));
  assert.ok(js.includes("actionKey: 'quality_patrol.desktop_approval.execute'"));
  assert.ok(js.includes('workbenchZone: true'));
  assert.ok(js.includes('promotionBatch.patchDraftReadyCount'));
  assert.ok(js.includes('promotionBatch.nextAction'));

  assert.ok(runbook.includes('latest promotion kind / status / draft PR ref / updatedAt'));
  assert.ok(runbook.includes('desktopPatrolSummary.promotionReview'));
  assert.ok(runbook.includes('desktopPatrolSummary.promotionApproval'));
  assert.ok(runbook.includes('desktopPatrolSummary.promotionBatch'));
  assert.ok(runbook.includes('remainingCommandCount'));
  assert.ok(runbook.includes('nextCommand'));
  assert.ok(runbook.includes('latestPromptRef'));
  assert.ok(runbook.includes('codeApplyEvidenceRef'));
  assert.ok(runbook.includes('evidenceRequirementCount'));
  assert.ok(runbook.includes('/api/admin/quality-patrol/desktop-approval/plan'));
  assert.ok(runbook.includes('/api/admin/quality-patrol/desktop-approval/execute'));
  assert.ok(runbook.includes('desktopPatrolPromotionApprovalEvidenceRequirementCount'));
  assert.ok(runbook.includes('desktopPatrolPromotionApprovalExpectedOutputCount'));
  assert.ok(runbook.includes('desktopPatrolPromotionApprovalStopConditionCount'));
  assert.ok(lineRunbook.includes('desktopPatrolSummary.promotion'));
  assert.ok(lineRunbook.includes('desktopPatrolSummary.promotionReview'));
  assert.ok(lineRunbook.includes('desktopPatrolSummary.promotionApproval'));
  assert.ok(lineRunbook.includes('desktopPatrolSummary.promotionBatch'));
  assert.ok(lineRunbook.includes('remainingCommandCount'));
  assert.ok(lineRunbook.includes('expectedOutputCount'));
  assert.ok(lineRunbook.includes('stopConditionCount'));
  assert.ok(lineRunbook.includes('nextCommand'));
  assert.ok(lineRunbook.includes('latestPromptRef'));
  assert.ok(lineRunbook.includes('codeApplyEvidenceRef'));
  assert.ok(lineRunbook.includes('evidenceRequirementCount'));
  assert.ok(lineRunbook.includes('managedFlowGuard + planHash + confirmToken'));
  assert.ok(ssot.includes('Latest promotion'));
  assert.ok(ssot.includes('Latest review bundle'));
  assert.ok(ssot.includes('Latest approval lane'));
  assert.ok(ssot.includes('Latest promotion batch'));
  assert.ok(ssot.includes('Plan next step'));
  assert.ok(ssot.includes('Run next step'));
  assert.ok(ssot.includes('Copy latest prompt path'));
  assert.ok(ssot.includes('Copy latest artifact path'));
  assert.ok(ssot.includes('Copy patch request path'));
  assert.ok(ssot.includes('Copy code apply task path'));
  assert.ok(ssot.includes('Copy code apply signoff path'));
  assert.ok(ssot.includes('Copy code apply record path'));
  assert.ok(ssot.includes('Copy code apply evidence path'));
  assert.ok(ssot.includes('Copy validation commands'));
  assert.ok(ssot.includes('Copy evidence prompt path'));
  assert.ok(ssot.includes('Copy evidence requirements'));
  assert.ok(ssot.includes('Copy expected outputs'));
  assert.ok(ssot.includes('Copy stop conditions'));
  assert.ok(ssot.includes('Copy operator instructions'));
  assert.ok(ssot.includes('Copy worktree path'));
  assert.ok(ssot.includes('Copy candidate edit paths'));
  assert.ok(ssot.includes('quality_patrol.desktop_approval.execute'));
  assert.ok(architecture.includes('promotion.latestArtifactKind'));
  assert.ok(architecture.includes('promotionReview.latestReviewArtifactKind'));
  assert.ok(architecture.includes('promotionApproval.approvalStage'));
  assert.ok(architecture.includes('promotionApproval.nextCommand'));
  assert.ok(architecture.includes('promotionApproval.latestPromptRef'));
  assert.ok(architecture.includes('promotionApproval.codeApplyEvidenceRef'));
  assert.ok(architecture.includes('Copy patch request path'));
  assert.ok(architecture.includes('Copy code apply task path'));
  assert.ok(architecture.includes('Copy code apply signoff path'));
  assert.ok(architecture.includes('Copy code apply record path'));
  assert.ok(architecture.includes('Copy code apply evidence path'));
  assert.ok(architecture.includes('promotionApproval.expectedOutputCount'));
  assert.ok(architecture.includes('promotionApproval.stopConditionCount'));
  assert.ok(architecture.includes('Copy evidence prompt path'));
  assert.ok(architecture.includes('Copy expected outputs'));
  assert.ok(architecture.includes('Copy stop conditions'));
  assert.ok(architecture.includes('/api/admin/quality-patrol/desktop-approval/execute'));
  assert.ok(architecture.includes('promotionBatch.batchRunId'));
  assert.ok(dataMap.includes('POST /api/admin/quality-patrol/desktop-approval/plan'));
  assert.ok(dataMap.includes('POST /api/admin/quality-patrol/desktop-approval/execute'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotion.latestArtifactKind'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionReview.latestReviewArtifactKind'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.approvalStage'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.nextCommand'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.latestPromptRef'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.codeApplyEvidenceRef'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.evidenceRequirementCount'));
  assert.ok(dataMap.includes('desktopPatrolPromotionApprovalEvidenceRequirementCount'));
  assert.ok(dataMap.includes('desktopPatrolPromotionApprovalExpectedOutputCount'));
  assert.ok(dataMap.includes('desktopPatrolPromotionApprovalStopConditionCount'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionApproval.remainingCommandCount'));
  assert.ok(dataMap.includes('desktopPatrolSummary.promotionBatch.batchRunId'));
});
