'use strict';

const { KPI_THRESHOLDS } = require('../kpi/constants');

const DETECTION_PROVENANCE = 'quality_patrol_detection';

const DETECTION_CONFIDENCE = Object.freeze({
  low: 'low',
  medium: 'medium',
  high: 'high'
});

const DETECTION_STATUS = Object.freeze({
  open: 'open',
  watching: 'watching',
  blocked: 'blocked',
  resolved: 'resolved'
});

const DETECTION_SEVERITY = Object.freeze({
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical'
});

const ISSUE_TYPE_BY_METRIC = Object.freeze({
  naturalness: 'conversation_quality',
  continuity: 'continuity',
  specificity: 'specificity',
  proceduralUtility: 'procedural_utility',
  knowledgeUse: 'knowledge_activation',
  fallbackRepetition: 'fallback_repetition',
  reviewableTranscriptRate: 'observation_blocker',
  userMessageAvailableRate: 'observation_blocker',
  assistantReplyAvailableRate: 'observation_blocker',
  priorContextSummaryAvailableRate: 'observation_blocker',
  transcriptAvailability: 'observation_blocker',
  observationBlockerRate: 'observation_blocker',
  blockedFollowupJudgementRate: 'observation_blocker',
  blockedKnowledgeJudgementRate: 'observation_blocker',
  broadAbstractEscapeRate: 'conversation_quality',
  followupContextResetRate: 'continuity',
  citySpecificityMissingRate: 'specificity',
  nextStepMissingRate: 'procedural_utility',
  repeatedTemplateResponseRate: 'fallback_repetition',
  knowledgeActivationMissingRate: 'knowledge_activation',
  savedFaqUnusedRate: 'knowledge_activation',
  cityPackUnusedRate: 'knowledge_activation',
  conciergeDirectAnswerMissingRate: 'procedural_utility',
  conciergeContextCarryMissingRate: 'continuity',
  conciergeKnowledgeBypassRate: 'knowledge_activation',
  conciergeTemplateOveruseRate: 'fallback_repetition',
  genericLoopFixedReplyRate: 'fallback_repetition',
  detailFormatDropRate: 'procedural_utility',
  transformSourceDropRate: 'continuity',
  deepenResetRate: 'continuity',
  messageOnlyViolatedRate: 'procedural_utility',
  correctionIgnoredRate: 'continuity',
  mixedDomainCollapseRate: 'continuity',
  cityOverclaimRate: 'specificity',
  followupOveraskRate: 'procedural_utility',
  internalLabelLeakRate: 'conversation_quality',
  commandBoundaryCollisionRate: 'continuity',
  punctuationAnomalyRate: 'conversation_quality',
  parrotEchoRate: 'fallback_repetition'
});

const CATEGORY_BY_METRIC = Object.freeze({
  naturalness: 'naturalness_degraded',
  continuity: 'continuity_degraded',
  specificity: 'specificity_degraded',
  proceduralUtility: 'procedural_utility_degraded',
  knowledgeUse: 'knowledge_use_degraded',
  fallbackRepetition: 'fallback_repetition_elevated',
  reviewableTranscriptRate: 'reviewable_transcript_rate_low',
  userMessageAvailableRate: 'user_message_availability_low',
  assistantReplyAvailableRate: 'assistant_reply_availability_low',
  priorContextSummaryAvailableRate: 'prior_context_availability_low',
  transcriptAvailability: 'transcript_availability_low',
  observationBlockerRate: 'observation_blocker_rate_high',
  blockedFollowupJudgementRate: 'followup_judgement_blocked',
  blockedKnowledgeJudgementRate: 'knowledge_judgement_blocked',
  broadAbstractEscapeRate: 'broad_abstract_escape',
  followupContextResetRate: 'followup_context_reset',
  citySpecificityMissingRate: 'city_specificity_missing',
  nextStepMissingRate: 'next_step_missing',
  repeatedTemplateResponseRate: 'repeated_template_response',
  knowledgeActivationMissingRate: 'knowledge_activation_missing',
  savedFaqUnusedRate: 'saved_faq_unused',
  cityPackUnusedRate: 'city_pack_unused',
  conciergeDirectAnswerMissingRate: 'concierge_direct_answer_missing',
  conciergeContextCarryMissingRate: 'concierge_context_carry_missing',
  conciergeKnowledgeBypassRate: 'concierge_knowledge_bypass',
  conciergeTemplateOveruseRate: 'concierge_template_overuse',
  genericLoopFixedReplyRate: 'generic_loop_fixed_reply',
  detailFormatDropRate: 'detail_format_drop',
  transformSourceDropRate: 'transform_source_drop',
  deepenResetRate: 'deepen_reset',
  messageOnlyViolatedRate: 'message_only_violated',
  correctionIgnoredRate: 'correction_ignored',
  mixedDomainCollapseRate: 'mixed_domain_collapse',
  cityOverclaimRate: 'city_scope_overclaim',
  followupOveraskRate: 'followup_overask',
  internalLabelLeakRate: 'internal_label_leak',
  commandBoundaryCollisionRate: 'command_boundary_collision',
  punctuationAnomalyRate: 'punctuation_anomaly',
  parrotEchoRate: 'parrot_echo'
});

const ISSUE_CODE_BY_METRIC = Object.freeze({
  naturalness: 'QP_NATURALNESS_DEGRADED',
  continuity: 'QP_CONTINUITY_DEGRADED',
  specificity: 'QP_SPECIFICITY_DEGRADED',
  proceduralUtility: 'QP_PROCEDURAL_UTILITY_DEGRADED',
  knowledgeUse: 'QP_KNOWLEDGE_USE_DEGRADED',
  fallbackRepetition: 'QP_FALLBACK_REPETITION_ELEVATED',
  reviewableTranscriptRate: 'QP_REVIEWABLE_TRANSCRIPT_RATE_LOW',
  userMessageAvailableRate: 'QP_USER_MESSAGE_AVAILABILITY_LOW',
  assistantReplyAvailableRate: 'QP_ASSISTANT_REPLY_AVAILABILITY_LOW',
  priorContextSummaryAvailableRate: 'QP_PRIOR_CONTEXT_AVAILABILITY_LOW',
  transcriptAvailability: 'QP_TRANSCRIPT_AVAILABILITY_LOW',
  observationBlockerRate: 'QP_OBSERVATION_BLOCKER_RATE_HIGH',
  blockedFollowupJudgementRate: 'QP_FOLLOWUP_JUDGEMENT_BLOCKED',
  blockedKnowledgeJudgementRate: 'QP_KNOWLEDGE_JUDGEMENT_BLOCKED',
  broadAbstractEscapeRate: 'QP_BROAD_ABSTRACT_ESCAPE',
  followupContextResetRate: 'QP_FOLLOWUP_CONTEXT_RESET',
  citySpecificityMissingRate: 'QP_CITY_SPECIFICITY_MISSING',
  nextStepMissingRate: 'QP_NEXT_STEP_MISSING',
  repeatedTemplateResponseRate: 'QP_REPEATED_TEMPLATE_RESPONSE',
  knowledgeActivationMissingRate: 'QP_KNOWLEDGE_ACTIVATION_MISSING',
  savedFaqUnusedRate: 'QP_SAVED_FAQ_UNUSED',
  cityPackUnusedRate: 'QP_CITY_PACK_UNUSED',
  conciergeDirectAnswerMissingRate: 'QP_CONCIERGE_DIRECT_ANSWER_MISSING',
  conciergeContextCarryMissingRate: 'QP_CONCIERGE_CONTEXT_CARRY_MISSING',
  conciergeKnowledgeBypassRate: 'QP_CONCIERGE_KNOWLEDGE_BYPASS',
  conciergeTemplateOveruseRate: 'QP_CONCIERGE_TEMPLATE_OVERUSE',
  genericLoopFixedReplyRate: 'QP_GENERIC_LOOP_FIXED_REPLY',
  detailFormatDropRate: 'QP_DETAIL_FORMAT_DROP',
  transformSourceDropRate: 'QP_TRANSFORM_SOURCE_DROP',
  deepenResetRate: 'QP_DEEPEN_RESET',
  messageOnlyViolatedRate: 'QP_MESSAGE_ONLY_VIOLATED',
  correctionIgnoredRate: 'QP_CORRECTION_IGNORED',
  mixedDomainCollapseRate: 'QP_MIXED_DOMAIN_COLLAPSE',
  cityOverclaimRate: 'QP_CITY_SCOPE_OVERCLAIM',
  followupOveraskRate: 'QP_FOLLOWUP_OVERASK',
  internalLabelLeakRate: 'QP_INTERNAL_LABEL_LEAK',
  commandBoundaryCollisionRate: 'QP_COMMAND_BOUNDARY_COLLISION',
  punctuationAnomalyRate: 'QP_PUNCTUATION_ANOMALY',
  parrotEchoRate: 'QP_PARROT_ECHO'
});

const TITLE_BY_METRIC = Object.freeze({
  naturalness: 'Japanese naturalness is degrading',
  continuity: 'Follow-up continuity is degrading',
  specificity: 'Answer specificity is degrading',
  proceduralUtility: 'Procedural utility is degrading',
  knowledgeUse: 'Knowledge activation is weak',
  fallbackRepetition: 'Fallback repetition risk is elevated',
  reviewableTranscriptRate: 'Reviewable transcript coverage is low',
  userMessageAvailableRate: 'User message coverage is low',
  assistantReplyAvailableRate: 'Assistant reply coverage is low',
  priorContextSummaryAvailableRate: 'Prior context coverage is low',
  transcriptAvailability: 'Transcript availability is low',
  observationBlockerRate: 'Observation blockers are elevated',
  blockedFollowupJudgementRate: 'Follow-up judgement is blocked',
  blockedKnowledgeJudgementRate: 'Knowledge judgement is blocked',
  broadAbstractEscapeRate: 'Broad answers are drifting into abstraction',
  followupContextResetRate: 'Follow-up answers are resetting context',
  citySpecificityMissingRate: 'City answers are missing specificity',
  nextStepMissingRate: 'Concrete next steps are missing',
  repeatedTemplateResponseRate: 'Repeated template responses are elevated',
  knowledgeActivationMissingRate: 'Knowledge activation is missing',
  savedFaqUnusedRate: 'Saved FAQ reuse is missing',
  cityPackUnusedRate: 'City Pack reuse is missing',
  conciergeDirectAnswerMissingRate: 'Concierge direct-answer execution is missing',
  conciergeContextCarryMissingRate: 'Concierge follow-up context carry is missing',
  conciergeKnowledgeBypassRate: 'Concierge path is bypassing available knowledge',
  conciergeTemplateOveruseRate: 'Concierge template overuse is elevated',
  genericLoopFixedReplyRate: 'Concierge generic fixed-reply loop is elevated',
  detailFormatDropRate: 'Concierge detail/output-format drops are elevated',
  transformSourceDropRate: 'Source-aware transform carry is failing',
  deepenResetRate: 'Deepen requests are resetting instead of going one layer deeper',
  messageOnlyViolatedRate: 'Message-only requests are drifting back into dialogue',
  correctionIgnoredRate: 'Concierge correction handling is failing',
  mixedDomainCollapseRate: 'Mixed-domain retention is failing',
  cityOverclaimRate: 'City answers are overclaiming beyond grounded specificity',
  followupOveraskRate: 'Concierge answers are asking unnecessary follow-up questions',
  internalLabelLeakRate: 'Internal labels are leaking into replies',
  commandBoundaryCollisionRate: 'Command boundary collisions are elevated',
  punctuationAnomalyRate: 'Punctuation anomalies are elevated',
  parrotEchoRate: 'Parrot-echo replies are elevated'
});

const BACKLOG_TEMPLATE_BY_METRIC = Object.freeze({
  naturalness: { title: 'Conversation naturalness repair', priority: 'P2', objective: 'Reduce machine-like phrasing and improve Japanese naturalness in replies.' },
  continuity: { title: 'Follow-up continuity repair', priority: 'P1', objective: 'Improve follow-up continuity so prior context is not reset.' },
  specificity: { title: 'Specificity grounding repair', priority: 'P1', objective: 'Increase grounded specificity in answers, especially for city and housing slices.' },
  proceduralUtility: { title: 'Procedural utility repair', priority: 'P1', objective: 'Ensure replies provide concrete next actions and execution order.' },
  knowledgeUse: { title: 'Knowledge activation repair', priority: 'P1', objective: 'Increase usage of available FAQ, saved FAQ, and City Pack knowledge signals.' },
  fallbackRepetition: { title: 'Fallback template diversification', priority: 'P1', objective: 'Reduce repeated fallback skeletons and diversify response templates.' },
  reviewableTranscriptRate: { title: 'Transcript coverage repair', priority: 'P1', objective: 'Raise reviewable transcript coverage for conversation quality patrol.' },
  userMessageAvailableRate: { title: 'Transcript coverage repair', priority: 'P1', objective: 'Raise reviewable transcript coverage for conversation quality patrol.' },
  assistantReplyAvailableRate: { title: 'Transcript coverage repair', priority: 'P1', objective: 'Raise reviewable transcript coverage for conversation quality patrol.' },
  priorContextSummaryAvailableRate: { title: 'Follow-up context coverage repair', priority: 'P1', objective: 'Improve prior-context coverage for follow-up reviewability.' },
  transcriptAvailability: { title: 'Transcript coverage repair', priority: 'P1', objective: 'Raise transcript availability so evaluator coverage is reliable.' },
  observationBlockerRate: { title: 'Observation coverage repair', priority: 'P1', objective: 'Reduce observation blockers so patrol can judge quality confidently.' },
  blockedFollowupJudgementRate: { title: 'Follow-up observation repair', priority: 'P1', objective: 'Reduce follow-up judgement blockers by improving context evidence availability.' },
  blockedKnowledgeJudgementRate: { title: 'Knowledge observation repair', priority: 'P1', objective: 'Reduce knowledge judgement blockers by improving candidate/evidence availability.' },
  broadAbstractEscapeRate: { title: 'Broad answer utility repair', priority: 'P1', objective: 'Prevent broad answers from collapsing into generic abstraction.' },
  followupContextResetRate: { title: 'Follow-up continuity repair', priority: 'P1', objective: 'Reduce follow-up context resets and preserve prior context in answers.' },
  citySpecificityMissingRate: { title: 'City grounding selection repair', priority: 'P1', objective: 'Increase city-specific grounding and City Pack usage in city answers.' },
  nextStepMissingRate: { title: 'Next-step utility repair', priority: 'P1', objective: 'Ensure answers end with concrete next-step guidance.' },
  repeatedTemplateResponseRate: { title: 'Fallback template diversification', priority: 'P1', objective: 'Reduce repeated template responses in generic fallback paths.' },
  knowledgeActivationMissingRate: { title: 'Knowledge activation repair', priority: 'P1', objective: 'Increase activation of available knowledge-backed candidates.' },
  savedFaqUnusedRate: { title: 'Saved FAQ activation repair', priority: 'P2', objective: 'Increase reuse of saved FAQ candidates when they are available.' },
  cityPackUnusedRate: { title: 'City Pack activation repair', priority: 'P1', objective: 'Increase reuse of City Pack candidates when they are available.' },
  conciergeDirectAnswerMissingRate: { title: 'Concierge direct-answer repair', priority: 'P1', objective: 'Restore direct-answer-first execution in concierge response paths.' },
  conciergeContextCarryMissingRate: { title: 'Concierge context-carry repair', priority: 'P1', objective: 'Increase follow-up context carry reliability in concierge path.' },
  conciergeKnowledgeBypassRate: { title: 'Concierge knowledge-bypass repair', priority: 'P1', objective: 'Prevent concierge answers from skipping available grounded candidates.' },
  conciergeTemplateOveruseRate: { title: 'Concierge template diversification', priority: 'P1', objective: 'Reduce repetitive concierge template reuse across replies.' },
  genericLoopFixedReplyRate: { title: 'Concierge generic-loop repair', priority: 'P1', objective: 'Stop concierge replies from resetting into a fixed generic skeleton.' },
  detailFormatDropRate: { title: 'Concierge detail/form repair', priority: 'P1', objective: 'Preserve requested detail and output form through the final reply.' },
  transformSourceDropRate: { title: 'Source-transform carry repair', priority: 'P1', objective: 'Keep source facts intact through rewrite and message-only transforms.' },
  deepenResetRate: { title: 'Deepen-response repair', priority: 'P1', objective: 'Stop deepen requests from collapsing back into generic resets.' },
  messageOnlyViolatedRate: { title: 'Message-only compliance repair', priority: 'P1', objective: 'Keep message-only requests in a single usable outbound message form.' },
  correctionIgnoredRate: { title: 'Correction supremacy repair', priority: 'P1', objective: 'Ensure explicit user corrections override prior context.' },
  mixedDomainCollapseRate: { title: 'Mixed-domain retention repair', priority: 'P1', objective: 'Keep both required domains present when the request demands it.' },
  cityOverclaimRate: { title: 'City scope overclaim repair', priority: 'P1', objective: 'Block city-specific claims when exact city grounding is not satisfied.' },
  followupOveraskRate: { title: 'Follow-up overask repair', priority: 'P1', objective: 'Suppress unnecessary ask-backs when the request is already answerable.' },
  internalLabelLeakRate: { title: 'Internal label leak repair', priority: 'P1', objective: 'Remove internal routing labels from user-visible replies.' },
  commandBoundaryCollisionRate: { title: 'Command boundary repair', priority: 'P1', objective: 'Prevent natural-language requests from colliding with command-only handling.' },
  punctuationAnomalyRate: { title: 'Punctuation normalization repair', priority: 'P2', objective: 'Eliminate user-visible punctuation anomalies in replies.' },
  parrotEchoRate: { title: 'Parrot-echo repair', priority: 'P1', objective: 'Advance the conversation instead of repeating the prior assistant line.' }
});

const METRIC_THRESHOLDS = Object.freeze({
  naturalness: KPI_THRESHOLDS.signal,
  continuity: KPI_THRESHOLDS.signal,
  specificity: KPI_THRESHOLDS.signal,
  proceduralUtility: KPI_THRESHOLDS.signal,
  knowledgeUse: KPI_THRESHOLDS.signal,
  fallbackRepetition: KPI_THRESHOLDS.repetitionRisk,
  reviewableTranscriptRate: KPI_THRESHOLDS.availability,
  userMessageAvailableRate: KPI_THRESHOLDS.availability,
  assistantReplyAvailableRate: KPI_THRESHOLDS.availability,
  priorContextSummaryAvailableRate: KPI_THRESHOLDS.availability,
  transcriptAvailability: KPI_THRESHOLDS.availability,
  observationBlockerRate: KPI_THRESHOLDS.blockerRate,
  blockedFollowupJudgementRate: KPI_THRESHOLDS.blockerRate,
  blockedKnowledgeJudgementRate: KPI_THRESHOLDS.blockerRate,
  broadAbstractEscapeRate: KPI_THRESHOLDS.issueRate,
  followupContextResetRate: KPI_THRESHOLDS.issueRate,
  citySpecificityMissingRate: KPI_THRESHOLDS.issueRate,
  nextStepMissingRate: KPI_THRESHOLDS.issueRate,
  repeatedTemplateResponseRate: KPI_THRESHOLDS.issueRate,
  knowledgeActivationMissingRate: KPI_THRESHOLDS.issueRate,
  savedFaqUnusedRate: KPI_THRESHOLDS.issueRate,
  cityPackUnusedRate: KPI_THRESHOLDS.issueRate,
  conciergeDirectAnswerMissingRate: KPI_THRESHOLDS.issueRate,
  conciergeContextCarryMissingRate: KPI_THRESHOLDS.issueRate,
  conciergeKnowledgeBypassRate: KPI_THRESHOLDS.issueRate,
  conciergeTemplateOveruseRate: KPI_THRESHOLDS.issueRate,
  genericLoopFixedReplyRate: KPI_THRESHOLDS.issueRate,
  detailFormatDropRate: KPI_THRESHOLDS.issueRate,
  transformSourceDropRate: KPI_THRESHOLDS.issueRate,
  deepenResetRate: KPI_THRESHOLDS.issueRate,
  messageOnlyViolatedRate: KPI_THRESHOLDS.issueRate,
  correctionIgnoredRate: KPI_THRESHOLDS.issueRate,
  mixedDomainCollapseRate: KPI_THRESHOLDS.issueRate,
  cityOverclaimRate: KPI_THRESHOLDS.issueRate,
  followupOveraskRate: KPI_THRESHOLDS.issueRate,
  internalLabelLeakRate: KPI_THRESHOLDS.issueRate,
  commandBoundaryCollisionRate: KPI_THRESHOLDS.issueRate,
  punctuationAnomalyRate: KPI_THRESHOLDS.issueRate,
  parrotEchoRate: KPI_THRESHOLDS.issueRate
});

const SIGNAL_METRIC_KEYS = Object.freeze([
  'naturalness',
  'continuity',
  'specificity',
  'proceduralUtility',
  'knowledgeUse',
  'fallbackRepetition'
]);

const AVAILABILITY_METRIC_KEYS = Object.freeze([
  'reviewableTranscriptRate',
  'userMessageAvailableRate',
  'assistantReplyAvailableRate',
  'priorContextSummaryAvailableRate',
  'transcriptAvailability'
]);

const BLOCKER_METRIC_KEYS = Object.freeze([
  'observationBlockerRate',
  'blockedFollowupJudgementRate',
  'blockedKnowledgeJudgementRate'
]);

const ISSUE_RATE_METRIC_KEYS = Object.freeze([
  'broadAbstractEscapeRate',
  'followupContextResetRate',
  'citySpecificityMissingRate',
  'nextStepMissingRate',
  'repeatedTemplateResponseRate',
  'knowledgeActivationMissingRate',
  'savedFaqUnusedRate',
  'cityPackUnusedRate',
  'conciergeDirectAnswerMissingRate',
  'conciergeContextCarryMissingRate',
  'conciergeKnowledgeBypassRate',
  'conciergeTemplateOveruseRate'
  ,
  'genericLoopFixedReplyRate',
  'detailFormatDropRate',
  'transformSourceDropRate',
  'deepenResetRate',
  'messageOnlyViolatedRate',
  'correctionIgnoredRate',
  'mixedDomainCollapseRate',
  'cityOverclaimRate',
  'followupOveraskRate',
  'internalLabelLeakRate',
  'commandBoundaryCollisionRate',
  'punctuationAnomalyRate',
  'parrotEchoRate'
]);

module.exports = {
  DETECTION_PROVENANCE,
  DETECTION_CONFIDENCE,
  DETECTION_STATUS,
  DETECTION_SEVERITY,
  ISSUE_TYPE_BY_METRIC,
  CATEGORY_BY_METRIC,
  ISSUE_CODE_BY_METRIC,
  TITLE_BY_METRIC,
  BACKLOG_TEMPLATE_BY_METRIC,
  METRIC_THRESHOLDS,
  SIGNAL_METRIC_KEYS,
  AVAILABILITY_METRIC_KEYS,
  BLOCKER_METRIC_KEYS,
  ISSUE_RATE_METRIC_KEYS
};
