#!/usr/bin/env bash
set -euo pipefail

# Comprehensive audit runner.
# - Designed to be deterministic in CI (GitHub Actions).
# - Locally, Docker-based scans are skipped if Docker isn't available.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${ROOT_DIR}/artifacts/audit"
OUT_DIR_REL="artifacts/audit"

mkdir -p "$OUT_DIR"

log() { printf "[audit] %s\n" "$*" >&2; }

fail() {
  log "FAIL: $*"
  exit 1
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

in_ci() {
  [[ "${CI:-}" == "1" || "${GITHUB_ACTIONS:-}" == "true" ]]
}

run_step() {
  local name="$1"
  shift
  log "== ${name} =="
  "$@"
}

write_summary_header() {
  cat > "${OUT_DIR}/summary.md" <<'MD'
# Audit Summary

This folder is generated by `tools/audit/run_audit.sh`.

MD
}

append_summary() {
  printf "%s\n" "$*" >> "${OUT_DIR}/summary.md"
}

write_summary_header
append_summary "- utc: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
append_summary "- git_sha: $(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"
append_summary ""

run_step "npm ci" bash -lc "cd \"$ROOT_DIR\" && npm ci" \
  || fail "npm ci failed"

run_step "preflight" bash -lc "cd \"$ROOT_DIR\" && npm run preflight" \
  || fail "preflight failed"

run_step "tests" bash -lc "cd \"$ROOT_DIR\" && npm test" \
  || fail "tests failed"

run_step "docs check" bash -lc "cd \"$ROOT_DIR\" && npm run test:docs" \
  || fail "docs check failed"

run_step "trace smoke" bash -lc "cd \"$ROOT_DIR\" && TRACE_SMOKE_WRITE_EVIDENCE=0 TRACE_SMOKE_EVIDENCE_PATH=/tmp/trace_smoke_evidence.md npm run test:trace-smoke" \
  || fail "trace smoke failed"

run_step "ops smoke" bash -lc "cd \"$ROOT_DIR\" && npm run test:ops-smoke" \
  || fail "ops smoke failed"

run_step "npm audit (high+)" bash -lc "cd \"$ROOT_DIR\" && npm audit --audit-level=high --json > \"$OUT_DIR/npm-audit.json\"" \
  || fail "npm audit found high/critical vulnerabilities (see artifacts/audit/npm-audit.json)"

run_step "duplicates" bash -lc "cd \"$ROOT_DIR\" && python3 tools/audit/duplicate_files.py > \"$OUT_DIR/duplicates.txt\"" \
  || fail "duplicate scan failed"

run_step "GO_SCOPE evidence (required scope)" bash -lc "cd \"$ROOT_DIR\" && python3 tools/audit/go_scope_evidence_check.py > \"$OUT_DIR/evidence_required_scope.txt\"" \
  || fail "GO_SCOPE evidence check failed"

run_step "retention risk budget check" bash -lc "cd \"$ROOT_DIR\" && npm run retention-risk:check > \"$OUT_DIR/retention-risk-check.txt\"" \
  || fail "retention risk check failed"

DOCKER_GITLEAKS_IMAGE="${DOCKER_GITLEAKS_IMAGE:-zricethezav/gitleaks:v8.30.0}"
DOCKER_SEMGREP_IMAGE="${DOCKER_SEMGREP_IMAGE:-returntocorp/semgrep:1.151.0}"
DOCKER_OSV_IMAGE="${DOCKER_OSV_IMAGE:-ghcr.io/google/osv-scanner:v2.3.2}"

if have_cmd docker; then
  run_step "gitleaks" bash -lc "cd \"$ROOT_DIR\" && docker run --rm -v \"$ROOT_DIR:/repo\" -w /repo \"$DOCKER_GITLEAKS_IMAGE\" detect --no-git --redact --report-format json --report-path \"/repo/${OUT_DIR_REL}/gitleaks.json\""

  # Semgrep downloads rules for auto config. In CI that's OK; locally you can skip by setting SKIP_SEMGREP=1.
  if [[ "${SKIP_SEMGREP:-}" != "1" ]]; then
    log "== semgrep (sarif) =="
    set +e
    bash -lc "cd \"$ROOT_DIR\" && docker run --rm -v \"$ROOT_DIR:/repo\" -w /repo \"$DOCKER_SEMGREP_IMAGE\" semgrep --config=auto --sarif --output \"/repo/${OUT_DIR_REL}/semgrep.sarif\" --metrics=off"
    code=$?
    set -e
    if [ "$code" -ne 0 ]; then
      log "WARN: semgrep exited with code=$code (treating as non-blocking for now)"
      append_summary "- WARN: semgrep exit code=$code (see artifacts/audit/semgrep.sarif)"
    fi
  else
    log "semgrep skipped (SKIP_SEMGREP=1)"
  fi

  run_step "osv-scanner (lockfile)" bash -lc "cd \"$ROOT_DIR\" && docker run --rm -v \"$ROOT_DIR:/repo\" -w /repo \"$DOCKER_OSV_IMAGE\" scan --lockfile package-lock.json --format json --output \"/repo/${OUT_DIR_REL}/osv.json\""
else
  if in_ci; then
    fail "docker is required in CI for gitleaks/semgrep/osv-scanner"
  fi
  log "docker not available; skipping gitleaks/semgrep/osv-scanner (local only)"
  append_summary "- WARN: docker missing; skipped gitleaks/semgrep/osv-scanner"
fi

append_summary "## Results"
append_summary "- PASS: core tests and gates"
append_summary ""
log "done: ${OUT_DIR}"
