'use strict';

const { spawnSync } = require('node:child_process');

const LOOKBACK_COMMITS = 120;

const WATCHLIST = Object.freeze([
  {
    path: 'docs/REPO_AUDIT_INPUTS/audit_inputs_manifest.json',
    reason: 'docs artifact aggregate tends to conflict after stacked internal-job merges',
    generators: ['npm run docs-artifacts:generate', 'npm run audit-inputs:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/load_risk.json',
    reason: 'load-risk regeneration commonly changes after shared route and docs updates',
    generators: ['npm run docs-artifacts:generate', 'npm run load-risk:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/missing_index_surface.json',
    reason: 'index surface snapshots drift when internal route coverage changes',
    generators: ['npm run docs-artifacts:generate', 'npm run missing-index-surface:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/supervisor_master.json',
    reason: 'supervisor summary is regenerated by multiple docs and audit flows',
    generators: ['npm run docs-artifacts:generate', 'node scripts/generate_supervisor_master.js']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/repo_map_ui.json',
    reason: 'repo map output shifts when route and docs surfaces move together',
    generators: ['npm run repo-map:generate', 'npm run docs-artifacts:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/retention_risk.json',
    reason: 'retention watchpoints are regenerated during structural cleanup passes',
    generators: ['npm run retention-risk:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/structure_risk.json',
    reason: 'structure-risk output is sensitive to stacked branch docs regeneration',
    generators: ['npm run structure-risk:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/feature_map.json',
    reason: 'feature map changes when internal-job route metadata and docs move together',
    generators: ['npm run audit-inputs:generate']
  },
  {
    path: 'docs/REPO_AUDIT_INPUTS/kill_switch_points.json',
    reason: 'kill-switch metadata conflicts when internal-job outcome docs land in parallel',
    generators: ['npm run audit-inputs:generate']
  },
  {
    path: 'docs/KILLSWITCH_DEPENDENCY_MAP.md',
    reason: 'kill-switch dependency narrative is frequently regenerated alongside audit inputs',
    generators: ['npm run docs-artifacts:generate']
  }
]);

const RECOMMENDED_SEQUENCE = Object.freeze([
  'git fetch origin && git merge --no-edit origin/main',
  'npm run audit-core:generate',
  'npm run repo-map:generate',
  'npm run docs-artifacts:generate',
  'npm run load-risk:generate',
  'npm run missing-index-surface:generate',
  'npm run retention-risk:generate',
  'npm run structure-risk:generate',
  'node scripts/generate_supervisor_master.js',
  'npm run audit-inputs:generate',
  'npm run test:docs',
  'npm run catchup:drift-check'
]);

function collectHotspotCounts(paths) {
  const run = spawnSync(
    'git',
    ['log', '--name-only', '--format=', '-n', String(LOOKBACK_COMMITS)],
    { encoding: 'utf8' }
  );

  if (run.status !== 0) {
    throw new Error(run.stderr || run.stdout || 'failed to collect git history');
  }

  const counts = new Map();
  paths.forEach((entry) => counts.set(entry, 0));

  String(run.stdout || '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .forEach((line) => {
      if (counts.has(line)) {
        counts.set(line, counts.get(line) + 1);
      }
    });

  return counts;
}

function main() {
  const counts = collectHotspotCounts(WATCHLIST.map((entry) => entry.path));
  const payload = {
    watchlistVersion: 'internal_job_conflict_watchlist.v1',
    scope: 'internal_job_shared_artifacts',
    lookbackCommits: LOOKBACK_COMMITS,
    hotspots: WATCHLIST.map((entry) => ({
      path: entry.path,
      reason: entry.reason,
      generators: entry.generators,
      recentCommitTouches: counts.get(entry.path) || 0
    })).sort((left, right) => right.recentCommitTouches - left.recentCommitTouches || left.path.localeCompare(right.path)),
    recommendedSequence: RECOMMENDED_SEQUENCE
  };
  process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`);
}

main();
